name: Trigger auto deployment for container-app-d26yffn2pq55a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-d26yffn2pq55a-AutoDeployTrigger-03bfa62c-e1bc-42a1-bb64-e886cd6e5632.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPD26YFFN2PQ55A_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPD26YFFN2PQ55A_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPD26YFFN2PQ55A_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPD26YFFN2PQ55A_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPD26YFFN2PQ55A_REGISTRY_PASSWORD }}
          containerAppName: container-app-d26yffn2pq55a
          resourceGroup: todonodejspgsqlgoogleauth97f186a2
          imageToBuild: default/container-app-d26yffn2pq55a:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


